### ISSUE TITLE
How to play?

### ISSUE THREAD

**Issue by TheBearodactyl** [Smooth-E/infinidash#1]

**Comment by Smooth-E** [comment]
Added a link to the playable demo on itch. Please note that it might be outdated in relation to the code.
As of now, the game is just an early prototype. You can compile it yourself, if you want. It uses Unity 2021.3.24 right now.

**Comment by TheBearodactyl** [comment]
> Added a link to the playable demo on itch. Please note that it might be outdated in relation to the code. As of now, the game is just an early prototype. You can compile it yourself, if you want. It uses Unity 2021.3.24 right now.

thanks :D
